#!/usr/bin/env bash
# retrospective.sh — 자동 회고 시스템
# forge build 완료 후 자동으로 회고 보고서를 생성
# Usage: source lib/retrospective.sh && retro_generate "인증 시스템 구현" "nex,ryn,kai"

GOLEM_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${GOLEM_ROOT}/lib/soul-parser.sh"
source "${GOLEM_ROOT}/lib/growth-log.sh"

# 회고 디렉토리
RETRO_DIR="${GOLEM_DIR:-${GOLEM_ROOT}/.golem}/retrospectives"

# 디렉토리 초기화
_retro_ensure_dir() {
  [ ! -d "$RETRO_DIR" ] && mkdir -p "$RETRO_DIR"
}

# 회고 보고서 생성
# retro_generate <task> <souls_csv> [session_data]
# session_data: "soul:result:files:tests:cost" 형식, 세미콜론 구분
retro_generate() {
  local task="$1"
  local souls_csv="$2"
  local session_data="${3:-}"

  _retro_ensure_dir

  local date=$(date +%Y-%m-%d)
  local ts=$(date -u +%Y-%m-%dT%H:%M:%S 2>/dev/null || date +%Y-%m-%dT%H:%M:%S)
  local slug=$(echo "$task" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9가-힣-' | cut -c1-40)
  local retro_file="${RETRO_DIR}/${date}_${slug}.md"

  # 헤더
  cat > "$retro_file" <<RETROEOF
# Retrospective: ${task}
> ${date} | SOULs: ${souls_csv}

---

## 결과 요약

RETROEOF

  # SOUL별 결과 수집
  local total_files=0
  local total_tests=0
  local total_cost="0.000"
  local success_count=0
  local fail_count=0
  local soul_results=""

  IFS=',' read -ra soul_arr <<< "$souls_csv"
  for s in "${soul_arr[@]}"; do
    s=$(echo "$s" | tr -d ' ')
    [ -z "$s" ] && continue

    local soul_file=$(_resolve_soul_file "$s")
    [ ! -f "$soul_file" ] && continue
    soul_parse "$soul_file"

    local task_count=$(growth_log_task_count "$s")
    local rate=$(growth_log_success_rate "$s")
    local streak=$(growth_log_streak "$s")

    # 최근 태스크 정보 (growth-log 마지막 항목)
    local log_file="${GROWTH_DIR:-${GOLEM_DIR:-${GOLEM_ROOT}/.golem}/growth-log}/${s}.jsonl"
    local last_result="—"
    local last_files=0
    local last_tests=0
    local last_cost="0.000"
    if [ -f "$log_file" ]; then
      local last_line=$(tail -1 "$log_file")
      last_result=$(echo "$last_line" | grep -o '"result":"[^"]*"' | sed 's/"result":"//;s/"//')
      last_files=$(echo "$last_line" | grep -o '"files_changed":[0-9]*' | cut -d: -f2)
      last_tests=$(echo "$last_line" | grep -o '"tests_passed":[0-9]*' | cut -d: -f2)
      last_cost=$(echo "$last_line" | grep -o '"cost_usd":[0-9.]*' | cut -d: -f2)
      last_files=${last_files:-0}
      last_tests=${last_tests:-0}
      last_cost=${last_cost:-0.000}
    fi

    total_files=$((total_files + last_files))
    total_tests=$((total_tests + last_tests))
    total_cost=$(echo "$total_cost $last_cost" | awk '{printf "%.3f", $1+$2}')

    if [ "$last_result" = "success" ]; then
      success_count=$((success_count + 1))
    else
      fail_count=$((fail_count + 1))
    fi

    cat >> "$retro_file" <<SOULEOF
| ${SOUL_NAME} (${SOUL_ROLE}) | ${last_result} | ${last_files}파일 | ${last_tests}테스트 | \$${last_cost} | 연속 ${streak} |
SOULEOF
  done

  # 요약 테이블 헤더 삽입 (결과 앞에)
  local tmp_file="${retro_file}.tmp"
  head -7 "$retro_file" > "$tmp_file"
  echo "| SOUL | 결과 | 파일 | 테스트 | 비용 | 무결함 |" >> "$tmp_file"
  echo "|------|------|------|--------|------|--------|" >> "$tmp_file"
  tail -n +8 "$retro_file" >> "$tmp_file"
  mv "$tmp_file" "$retro_file"

  cat >> "$retro_file" <<TOTALEOF

**합계**: ${success_count}성공 / ${fail_count}실패 | ${total_files}파일 | ${total_tests}테스트 | \$${total_cost}

---

## 잘된 점

TOTALEOF

  # 잘된 점 자동 판단
  if [ "$fail_count" -eq 0 ]; then
    echo "- 전체 SOUL 성공 (무결함)" >> "$retro_file"
  fi
  if [ "$total_tests" -gt 0 ]; then
    echo "- 테스트 ${total_tests}개 작성/통과" >> "$retro_file"
  fi

  cat >> "$retro_file" <<IMPROVEEOF

## 개선할 점

IMPROVEEOF

  # 개선점 자동 판단
  if [ "$fail_count" -gt 0 ]; then
    echo "- ${fail_count}개 SOUL 태스크 실패 — 태스크 분해 또는 SOUL 매칭 재검토" >> "$retro_file"
  fi
  if [ "$total_tests" -eq 0 ]; then
    echo "- 테스트 미작성 — 다음에는 테스트 동반 필수" >> "$retro_file"
  fi

  cat >> "$retro_file" <<NEXTEOF

## 다음에 적용할 것

- (빌드 완료 후 수동 또는 AI가 자동 기입)

---

*Generated by GolemGarden Retrospective System*
NEXTEOF

  echo "[retro] 회고 생성: ${retro_file}"
  echo ""
  cat "$retro_file"
}

# 회고 목록 조회
retro_list() {
  _retro_ensure_dir

  echo "=== GolemGarden Retrospectives ==="
  echo ""
  printf "%-14s %-40s %s\n" "Date" "Task" "File"
  printf "%-14s %-40s %s\n" "----" "----" "----"

  for retro_file in "${RETRO_DIR}"/*.md; do
    [ -f "$retro_file" ] || continue
    local name=$(basename "$retro_file" .md)
    local date=$(echo "$name" | cut -c1-10)
    local task_slug=$(echo "$name" | cut -c12-)
    printf "%-14s %-40s %s\n" "$date" "$task_slug" "$(basename "$retro_file")"
  done
}

# 최근 회고 보기
retro_latest() {
  _retro_ensure_dir

  local latest=$(ls -t "${RETRO_DIR}"/*.md 2>/dev/null | head -1)
  if [ -z "$latest" ]; then
    echo "[retro] 회고 없음"
    return
  fi

  cat "$latest"
}

# 회고 트렌드 (누적 통계)
retro_trend() {
  _retro_ensure_dir

  local total_retros=0
  local total_cost="0.000"

  echo "=== GolemGarden Retrospective Trend ==="
  echo ""

  for retro_file in "${RETRO_DIR}"/*.md; do
    [ -f "$retro_file" ] || continue
    total_retros=$((total_retros + 1))
    # 비용 추출 (합계 줄에서)
    local cost=$(grep '^\*\*합계\*\*' "$retro_file" | grep -o '\$[0-9.]*' | tr -d '$' | tail -1)
    cost=${cost:-0.000}
    total_cost=$(echo "$total_cost $cost" | awk '{printf "%.3f", $1+$2}')
  done

  echo "  전체 회고: ${total_retros}회"
  echo "  누적 비용: \$${total_cost}"
  if [ "$total_retros" -gt 0 ]; then
    local avg=$(echo "$total_cost $total_retros" | awk '{printf "%.3f", $1/$2}')
    echo "  회당 평균: \$${avg}"
  fi
}
